---
- name: "setup.yml"
  hosts: all
  gather_facts: yes

  tasks:
  - name: Update packages
    ansible.builtin.command:
      cmd: "dnf upgrade --refresh"
    when: ansible_os_family == "RedHat"
    become: yes

  - name: Upgrade all packages (RedHat)
    ansible.builtin.dnf:
      name: "*"
      state: latest
    when: ansible_os_family == "RedHat"
    become: yes

  - name: Install packages (RedHat)
    ansible.builtin.dnf:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - bash-completion
      - net-tools
      - curl
      - git
      - rsync
      - tcpdump
      - vim
      - wget
      - cloud-init
      - python3
      - python3-pip
    when: ansible_os_family == "RedHat"
    become: yes

  - name: Install vmware cloud-init
    ansible.builtin.shell:
      cmd: curl -sSL https://raw.githubusercontent.com/vmware/cloud-init-vmware-guestinfo/master/install.sh | sh -
    when: ansible_virtualization_type == "VMware"
    become: yes

  - name: Install open-vm-tools (RedHat)
    ansible.builtin.dnf:
      name: open-vm-tools
      state: latest
    when: 
      - ansible_os_family == "RedHat"
      - ansible_virtualization_type == "VMware"
    become: yes

  - name: Create vim configuration file
    ansible.builtin.file:
      path: /root/.vimrc
      state: touch
      owner: root
      group: root
      mode: 0644
    become: yes

  - name: Configure vim
    ansible.builtin.blockinfile:
      path: /root/.vimrc
      block: |
        set nocompatible
        set number
        set autoindent
        set tabstop=4
        set shiftwidth=4
        set expandtab
        syntax on
        highlight Comment ctermfg=LightCyan
      marker: ""
      state: present
    become: yes
