---
# tasks file for docker-install role
- name: Install dependencies
  ansible.builtin.yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Create containerd config file
  ansible.builtin.file:
    path: "/etc/modules-load.d/containerd.conf"
    state: "touch"

- name: Add conf for containerd
  ansible.builtin.blockinfile:
    path: "/etc/modules-load.d/containerd.conf"
    block: |
          overlay
          br_netfilter

- name: modprobe
  ansible.builtin.shell:
    cmd: "modprobe overlay; modprobe br_netfilter"

- name: Apply settings
  ansible.builtin.shell:
    cmd: sysctl --system

- name: Add Docker Repo
  ansible.builtin.shell:
    cmd: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"

- name: Install containerd
  ansible.builtin.yum:
    name: containerd.io
    state: latest

- name: Enable docker service
  ansible.builtin.service:
    name: containerd
    enabled: yes

- name: create containerd folder
  ansible.builtin.file:
    path: "/etc/containerd"
    state: directory

- name: Configure containerd
  ansible.builtin.shell:
    cmd: "containerd config default | sudo tee /etc/containerd/config.toml"

- name: Restart containerd service
  ansible.builtin.service:
    name: containerd
    state: restarted