# -*- mode: ruby -*-
# nvim: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do | config |

  config.vm.box = "dev-alma"

  config.ssh.username = "packer"
  config.ssh.password = "p4k3rRul3s"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.cpus = 2
  end

  config.vm.provision "ansible" do | ansible |
    ansible.playbook = "playbook.yml"
  end
  
  config.vm.define "dev-alma" do | alma |
    alma.vm.hostname = "alma.dev"
    alma.vm.network "public_network", ip: "192.168.0.101" # WAN bridged
  end

end
