---
# tasks file for sshd-config
- name: Print file
  ansible.builtin.debug:
    msg: "{{lookup('ansible.builtin.file', '/etc/ssh/sshd_config')}}"

- name: Allow password auth
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: '^PasswordAuthentication .*'
    line: 'PasswordAuthentication yes'
  become: yes

- name: sshd enabled
  ansible.builtin.service:
    name: sshd
    enabled: yes
  become: yes
