---
- name: "docker.yml"
  hosts: nodes

  vars:
    ports: 
      - "6443/tcp"
      - "2379/tcp"
      - "2380/tcp"
      - "10250/tcp"
      - "10251/tcp"
      - "10252/tcp"
      - "10255/tcp"
      - "8285/tcp"
  
  pre_tasks:
    - name: Node connection test
      ansible.builtin.debug:
        msg: "Hello from node"
      when: inventory_hostname != "master"

    - name: Master connection test
      ansible.builtin.debug:
        msg: "Hello from master"
      when: inventory_hostname == "master"

  roles:
    - role: docker-install
      become: yes
      tags:
        - never
    - role: kubernetes-install
      become: yes