---
- name: "docker.yml"
  hosts: nodes
  
  pre_tasks:
    - name: Node connection test
      ansible.builtin.debug:
        msg: "Hello from node"
      when: inventory_hostname != "master"

    - name: Master connection test
      ansible.builtin.debug:
        msg: "Hello from master"
      when: inventory_hostname == "master"

  roles:
    - role: docker-install
      become: yes