---
- name: "firewall.yml" 
  hosts: firewall
  gather_facts: yes

  pre_tasks:
    - name: set ipsec facts
      ansible.builtin.set_fact:
        ipsec: "{{ tunnel }}"
  
  roles:
    - role: ipsec

- hosts: localhost
  connection: local

  pre_tasks:
    - name: set ipsec facts
      ansible.builtin.set_fact:
        ipsec: "{{ ipsec | default({ 'bastion' : tunnel['bastion'] }) }}"
  roles:
    - role: ipsec
