---
- name: "firewall.yml" 
  hosts: firewall
  gather_facts: yes

  pre_tasks:
    - name: set ipsec facts
      ansible.builtin.set_fact:
        ipsec: "{{ tunnel }}"

    - name: install tcpdump
      ansible.builtin.yum:
        name: tcpdump
        state: latest
      become: yes
  
  roles:
    - role: ipsec-router

  post_tasks:
    - name: Enable IPv4 forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes
      become: yes


- hosts: localhost
  connection: local

  pre_tasks:
    - name: set ipsec facts
      ansible.builtin.set_fact:
        ipsec: "{{ ipsec | default({ 'bastion' : tunnel['bastion'] }) }}"

    - name: install tcpdump
      ansible.builtin.yum:
        name: tcpdump
        state: latest
      become: yes

  roles:
    - role: ipsec-host
