---
- name: "setup.yml" 
  hosts: firewall
  gather_facts: yes

  pre_tasks:
    - name: set ipsec facts
      ansible.builtin.set_fact:
        ipsec: "{{ tunnel }}"

    - name: install tcpdump
      ansible.builtin.yum:
        name: tcpdump
        state: latest
      become: yes

    - name: Enable IPv4 forwarding
      ansible.builtin.shell:
        cmd: "echo 1 > /proc/sys/net/ipv4/ip_forward"
      become: yes
  
  roles:
    - role: ipsec-router

  post_tasks:
    - name: Add static routes
      block:
        - name: Add static route from private to NAC
          ansible.builtin.command:
            cmd: "nmcli connection modify 'System ens33' +ipv4.routes '192.168.0.0/16 172.24.5.1'"

        - name: Reload connection
          ansible.builtin.command:
            cmd: "nmcli connection reload"

        - name: Turn NAC connection up
          ansible.builtin.command:
            cmd: "nmcli connection up 'System ens33'"
      become: yes

- hosts: localhost
  connection: local

  pre_tasks:
    - name: set ipsec facts
      ansible.builtin.set_fact:
        ipsec: "{{ ipsec | default({ 'bastion' : tunnel['bastion'] }) }}"

    - name: install tcpdump
      ansible.builtin.yum:
        name: tcpdump
        state: latest
      become: yes

  roles:
    - role: ipsec-host
